apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-chatbot
  namespace: iiitb-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-chatbot-fe
  template:
    metadata:
      labels:
        app: rag-chatbot-fe
    spec:
      containers:
        - name: rag-chatbot
          image: archis002/rag-chatbot:latest
          ports:
            - containerPort: 3000  # Change to your app's port
