apiVersion: v1
kind: Service
metadata:
  name: rag-chatbot-fe
  namespace: iiitb-chatbot
spec:
  selector:
    app: rag-chatbot-fe
  type: NodePort
  ports:
    - protocol: TCP
      port: 80            
      targetPort: 3000    
      nodePort: 30000     
