version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts  # Use full Jenkins controller
    container_name: jenkins-with-dind
    privileged: true  # Required for DinD
    user: root  # Ensures Jenkins has the correct permissions
    environment:
      - DOCKER_HOST=tcp://docker:2375  # Connect to the DinD container
    ports:
      - "8080:8080"  # Expose Jenkins UI
      - "50000:50000"  # For Jenkins agent connections (if needed)
      - "3000:3000"
    depends_on:
      - docker  # Ensure Docker starts first
    volumes:
      - jenkins_data:/var/jenkins_home  # Persistent Jenkins data
      - /var/run/docker.sock:/var/run/docker.sock  # Optional: Direct access to host Docker (alternative to DinD)

  docker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker
    privileged: true  # Allows running Docker daemon inside the container
    environment:
      - DOCKER_TLS_CERTDIR=  # Disable TLS for easier communication
    volumes:
      - dind_storage:/var/lib/docker  # Persistent Docker data

volumes:
  jenkins_data:
  dind_storage:

networks:
  dind_net:
    driver: bridge
